# Site settings
title: pfernandom
email: pfernandom@hotmail.com
description: "A blog about software architecture and development, and everything around that."
short_description:"Software architecture and security"
baseurl: ""
url: "http://pfernandom.github.io/"
twitter_username: pfernandom
github_username:  pfernandom
stackoverflow_username: pfernandom

# Build settings
markdown: kramdown
permalink: pretty
