# Site settings
title: pfernandom
email: pfernandom@hotmail.com
description: "A blog about software architecture and development, and everything around that."
baseurl: ""
url: "http://pfernandom.github.io/"
twitter_username: pfernandom
github_username:  pfernandom
stackoverflow_username: pfernandom

paginate: 4

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-sitemap